from pyexpat import model
from django.db import models

# Create your models here.
class QUESTION(models.Model):
    q1=models.IntegerField(blank=False,default=9)
    q2=models.IntegerField(blank=False,default=9)
    q3=models.IntegerField(blank=False,default=9)
    q4=models.IntegerField(blank=False,default=9)
    q5=models.IntegerField(blank=False,default=9)
    q6=models.IntegerField(blank=False,default=9)
    q7=models.IntegerField(blank=False,default=9)
    q8=models.IntegerField(blank=False,default=9)
    q9=models.IntegerField(blank=False,default=9)
    q10=models.IntegerField(blank=False,default=9)
    q11=models.IntegerField(blank=False,default=9)
    q12=models.IntegerField(blank=False,default=9)
    q13=models.IntegerField(blank=False,default=9)
    q14=models.IntegerField(blank=False,default=9)
    q15=models.IntegerField(blank=False,default=9)
    q16=models.IntegerField(blank=False,default=9)
    q17=models.IntegerField(blank=False,default=9)
    q18=models.IntegerField(blank=False,default=9)
    q19=models.IntegerField(blank=False,default=9)
    q20=models.IntegerField(blank=False,default=9)
    q21=models.IntegerField(blank=False,default=9)
    q22=models.IntegerField(blank=False,default=9)
    q23=models.IntegerField(blank=False,default=9)
    q24=models.IntegerField(blank=False,default=9)
    q25=models.IntegerField(blank=False,default=9)
    q26=models.IntegerField(blank=False,default=9)
    q27=models.IntegerField(blank=False,default=9)
    q28=models.IntegerField(blank=False,default=9)
    q29=models.IntegerField(blank=False,default=9)
    q30=models.IntegerField(blank=False,default=9)
    q31=models.IntegerField(blank=False,default=9)
    q32=models.IntegerField(blank=False,default=9)
    q33=models.IntegerField(blank=False,default=9)
    q34=models.IntegerField(blank=False,default=9)
    q35=models.IntegerField(blank=False,default=9)
    q36=models.IntegerField(blank=False,default=9)
    q37=models.IntegerField(blank=False,default=9)
    q38=models.IntegerField(blank=False,default=9)
    q39=models.IntegerField(blank=False,default=9)
    q40=models.IntegerField(blank=False,default=9)
    q41=models.IntegerField(blank=False,default=9)
    q42=models.IntegerField(blank=False,default=9)
    q43=models.IntegerField(blank=False,default=9)
    q44=models.IntegerField(blank=False,default=9)
    q45=models.IntegerField(blank=False,default=9)
    q46=models.IntegerField(blank=False,default=9)
    q47=models.IntegerField(blank=False,default=9)
    q48=models.IntegerField(blank=False,default=9)
    q49=models.IntegerField(blank=False,default=9)
    q50=models.IntegerField(blank=False,default=9)
    
class add(models.Model):
    mail=models.EmailField(blank=False)

class nomi(models.Model):
    name=models.CharField(max_length=30)
    msg=models.TextField(max_length=300)
    mail=models.EmailField(blank=False)
    sender_name=models.CharField(max_length=30)
