# Generated by Django 4.0.1 on 2022-01-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q2',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='question',
            name='q1',
            field=models.IntegerField(default=9),
        ),
    ]
