# Generated by Django 4.0.1 on 2022-01-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigapp', '0004_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='nomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('msg', models.TextField(max_length=300)),
                ('mail', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='add',
            name='msg',
        ),
        migrations.RemoveField(
            model_name='add',
            name='subject',
        ),
    ]
